### ISSUE TITLE
Curtin ZFS EFI Simple install

### ISSUE THREAD

**Issue by Makr91** [ubuntu/zsys-install#1]
Hello All,

I am terribly sorry if this is the wrong place but I have tried so many different configurations for tyring to get a Simple ZFS root installation on a single disk setup.

Could someone help me with this?

```
  storage:
   version: 1
   config:
     - id: sda
       type: disk
       ptable: gpt
       path: /dev/sda
       name: main_disk
       wipe: superblock
       grub_device: true
     - id: efi
       type: partition
       size: 2G
       number: 1
       device: sda
       flag: boot
       grub_device: true
     - id: sda1
       type: partition
       number: 2
       size: 15G
       device: sda
     - id: efi_format
       type: format
       fstype: fat32
       volume: efi
       label: efi
     - id: sda1_root
       type: format
       fstype: zfsroot
       volume: sda1
       label: 'rootfs'
     - id: sda1_mount
       type: mount
       path: /
       device: sda1_root
     - id: efi_mount
       device: efi_format
       path: /boot/efi
       type: mount
```

A configuration like this would work for me. I am using this to create a packer template (also autoinstaller for physical hosts down the line) and vagrant and I can get BIOS ZFS to work with no issue, but I can't seem to get over setting up a single disk EFI installation.

This is for a 21.04 images currently, Here is what the rest of my user-data file looks like:

Parts above this redacted for security reasons
```
  early-commands:
    - 'sudo apt-get install zfsutils-linux -y'
  packages:
    - build-essential
    - authbind
    - sendmail
    - mailutils
    - certbot
    - perl
    - wmctrl
    - xdotool
    - rsync
    - git
    - htop
    - aptitude
    - iotop
    - audispd-plugins
    - auditd
    - iftop
    - wget
    - tmux
    - curl
    - vim
    - zfs-auto-snapshot
    - nano
    - ncdu
    - python3-pip
    - deborphan
    - screen
    - ansible
    - sshpass
    - gcc
    - make
    - perl
    - net-tools
    - dkms
    - cockpit
  late-commands:
    - 'echo "vagrant ALL=(ALL) NOPASSWD: ALL" > /target/etc/sudoers.d/vagrant'
    - 'chmod 440 /target/etc/sudoers.d/vagrant'
    - 'sed -i "s/^.*requiretty/#Defaults requiretty/" /target/etc/sudoers'
    - 'sed -i.bak "s/^Prompt=.*$/Prompt=never/" /target/etc/update-manager/release-upgrades'
    - curtin in-target --target=/target -- apt-get -y install linux-headers-$(uname -r)
    - curtin in-target --target=/target -- apt-get update -y -qq
  keyboard:
    layout: us
    variant: ""
  apt:
      primary:
          - arches: [default]
            uri: http://archive.ubuntu.com/ubuntu/
  showtrace: true
```

**Comment by Makr91** [comment]
I was able to get UEFI working with a configuration below, however I noticed that it's creating the partitions as non native blocksizes. Is there  any way  to adjust this in the  zfsroot fstype?

       pool_properties:
          ashift: 12 

Something like that?

```
  showtrace: true
  storage:
   version: 1
   config:
     - id: sda
       type: disk
       ptable: gpt
       path: /dev/sda
       name: main_disk
       wipe: superblock
       grub_device: true
     - id: efi
       type: partition
       size: 2G
       number: 1
       device: sda
       flag: boot
       grub_device: true
     - id: sda1
       type: partition
       number: 2
       size: 7G
       device: sda
     - id: efi_format
       type: format
       fstype: fat32
       volume: efi
       label: efi
     - id: sda1_root
       type: format
       fstype: zfsroot
       volume: sda1
       label: 'rootfs'
     - id: sda1_mount
       type: mount
       path: /
       device: sda1_root
     - id: efi_mount
       device: efi_format
       path: /boot/efi
       type: mount
```
